language: go

go:
  - 1.8.x
  - 1.9.x

install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get github.com/mattn/goveralls

script:
  - gometalinter ./...
  - $GOPATH/bin/goveralls -service=travis-ci